// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AdminArticleListReq struct {
	Page   int `form:"page,default=1"`
	Size   int `form:"size,default=10"`
	Status int `form:"status,default=-1"` // -1=全部 0=草稿 1=发布 2=隐藏（不用 optional：0 和"不传"分不开）
}

type AdminArticleListResp struct {
	List  []AdminArticleSummary `json:"list"`
	Total int64                 `json:"total"`
}

type AdminArticleSummary struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Slug        string `json:"slug"`
	Status      int    `json:"status"`
	Views       int64  `json:"views"`
	PublishedAt string `json:"publishedAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type AdminComment struct {
	Id           int64  `json:"id"`
	ArticleId    int64  `json:"articleId"`
	ArticleTitle string `json:"articleTitle"`
	ArticleSlug  string `json:"articleSlug"`
	ParentId     int64  `json:"parentId"`
	Nickname     string `json:"nickname"`
	Content      string `json:"content"`
	Status       int    `json:"status"`
	CreatedAt    string `json:"createdAt"`
}

type AdminCommentListReq struct {
	Page   int `form:"page,default=1"`
	Size   int `form:"size,default=10"`
	Status int `form:"status,default=-1"` // -1=全部 0=待审核 1=通过 2=垃圾
}

type AdminCommentListResp struct {
	List  []AdminComment `json:"list"`
	Total int64          `json:"total"`
}

type ArticleDetail struct {
	Id          int64   `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Summary     string  `json:"summary,optional"`
	Content     string  `json:"content"`
	CoverUrl    string  `json:"coverUrl,optional"`
	Views       int64   `json:"views"`
	PublishedAt string  `json:"publishedAt"`
	Tags        []TagVo `json:"tags"`
}

type ArticleDetailReq struct {
	Slug string `path:"slug"`
}

type ArticleIdReq struct {
	Id int64 `path:"id"`
}

type ArticleListReq struct {
	Page    int    `form:"page,default=1"`
	Size    int    `form:"size,default=10"`
	Keyword string `form:"keyword,optional"`
	Tag     string `form:"tag,optional"` // 按标签 slug 过滤
}

type ArticleListResp struct {
	List  []ArticleSummary `json:"list"`
	Total int64            `json:"total"`
}

type ArticleSaveReq struct {
	Id       int64    `json:"id,optional" path:"id"` // 更新走路径参数，新建不带
	Title    string   `json:"title"`
	Slug     string   `json:"slug"`
	Summary  string   `json:"summary,optional"`
	Content  string   `json:"content"`
	CoverUrl string   `json:"coverUrl,optional"`
	Status   int      `json:"status,default=0"` // 0=草稿 1=发布 2=隐藏
	Tags     []string `json:"tags,optional"`    // 标签名列表；不存在的标签自动创建
}

type ArticleSummary struct {
	Id          int64   `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Summary     string  `json:"summary,optional"`
	CoverUrl    string  `json:"coverUrl,optional"`
	Views       int64   `json:"views"`
	PublishedAt string  `json:"publishedAt"`
	Tags        []TagVo `json:"tags"`
}

type Comment struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId,optional"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatarUrl,optional"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type CommentAuditReq struct {
	Id     int64 `path:"id"`
	Status int   `json:"status"` // 1=通过 2=垃圾
}

type CommentIdReq struct {
	Id int64 `path:"id"`
}

type CommentListReq struct {
	Slug string `path:"slug"`
}

type CommentListResp struct {
	List  []Comment `json:"list"`
	Total int64     `json:"total"`
}

type CommentSaveReq struct {
	Slug     string `path:"slug"`
	Nickname string `json:"nickname,optional"` // 游客填；不填则用默认昵称
	Content  string `json:"content"`
	ParentId int64  `json:"parentId,optional"`
}

type EmptyResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"` // access token 有效期（秒）
}

type PasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ProfileResp struct {
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type ProfileSaveReq struct {
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type SiteConfigResp struct {
	SiteTitle string `json:"siteTitle"`
	Icp       string `json:"icp,optional"`
	GithubUrl string `json:"githubUrl,optional"`
}

type SiteConfigSaveReq struct {
	SiteTitle string `json:"siteTitle,optional"`
	Icp       string `json:"icp,optional"`
	GithubUrl string `json:"githubUrl,optional"`
}

type TagListResp struct {
	List []TagWithCount `json:"list"`
}

type TagVo struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type TagWithCount struct {
	Name  string `json:"name"`
	Slug  string `json:"slug"`
	Count int64  `json:"count"` // 该标签下已发布文章数
}

type UploadResp struct {
	Url string `json:"url"`
}
